### ISSUE TITLE
start error on ubuntu 20.04 

### ISSUE THREAD

**Issue by albertofwb** [alairack/Crazy-Link#1]
```python
# albert @ albert-TM1701 in ~/Downloads [15:50:31] 
$ ./crazy_link_linux
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "menu.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "game_scene.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "judge.py", line 15, in <module>
  File "settings.py", line 59, in __init__
  File "settings.py", line 65, in open_log_file
FileNotFoundError: [Errno 2] No such file or directory: './logs/game_logs.txt'
[16889] Failed to execute script 'main' due to unhandled exception!
```

**Comment by alairack** [comment]
此问题是由于我在表示路径时使用了"\"，它在linux上不适用；在linux上,open(file, "a") 函数并不能在没有此文件时创建文件

**Comment by alairack** [comment]
我已经把路径更换为"/"，它在linux和windows上都是支持的，并在open(log.txt, "a") 时 ，增加了try…catch.
